package sxr.model;
import sxr.model.DeliveryOrInvoicePeriod;
import sxr.model.OrderAndSalesOrderReference;
import sxr.model.PrecedingInvoiceReference;
import sxr.model.DespatchAdviceReference;
import sxr.model.ReceiptAdviceReference;
import sxr.model.TenderOrLotReference;
import sxr.model.ContractReference;
import sxr.model.AdditionalSupportingDocuments;
import sxr.model.ProjectReference;
import sxr.model.Seller;
import sxr.model.Buyer;
import sxr.model.Payee;
import sxr.model.SellerTaxRepresentativeParty;
import sxr.model.DeliveryInformation;
import sxr.model.PaymentInstructions;
import sxr.model.PaymentTerms;
import sxr.model.DocumentLevelAllowancesAndCharges;
import sxr.model.TaxTotal;
import sxr.model.DocumentTotals;
import sxr.model.InvoiceLine;

public class Invoice {
	private String specificationIdentifier;
	private String businessProcessType;
	private String invoiceNumber;
	private String invoiceIssueDate;
	private String paymentDueDate;
	private String invoiceTypeCode;
	private String invoiceNote;
	private String valueAddedTaxPointDate;
	private String invoiceCurrencyCode;
	private String vatAccountingCurrencyCode;
	private String buyerAccountingReference;
	private String buyerReference;
	private DeliveryOrInvoicePeriod deliveryOrInvoicePeriod;
	private OrderAndSalesOrderReference orderAndSalesOrderReference;
	private PrecedingInvoiceReference precedingInvoiceReference;
	private DespatchAdviceReference despatchAdviceReference;
	private ReceiptAdviceReference receiptAdviceReference;
	private TenderOrLotReference tenderOrLotReference;
	private ContractReference contractReference;
	private AdditionalSupportingDocuments additionalSupportingDocuments;
	private ProjectReference projectReference;
	private Seller seller;
	private Buyer buyer;
	private Payee payee;
	private SellerTaxRepresentativeParty sellerTaxRepresentativeParty;
	private DeliveryInformation deliveryInformation;
	private PaymentInstructions paymentInstructions;
	private PaymentTerms paymentTerms;
	private DocumentLevelAllowancesAndCharges documentLevelAllowancesAndCharges;
	private TaxTotal taxTotal;
	private DocumentTotals documentTotals;
	private InvoiceLine invoiceLine;
}
