// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DELIVERY_INFORMATION.proto
// Protobuf Java Version: 4.27.3

package com.example;

/**
 * Protobuf type {@code com.example.DELIVERY_INFORMATION}
 */
public final class DELIVERY_INFORMATION extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.example.DELIVERY_INFORMATION)
        DELIVERY_INFORMATIONOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 27,
                /* patch= */ 3,
                /* suffix= */ "",
                DELIVERY_INFORMATION.class.getName());
    }

    // Use DELIVERY_INFORMATION.newBuilder() to construct.
    private DELIVERY_INFORMATION(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private DELIVERY_INFORMATION() {
        dELIVERYINFORMATION_ = "";
        deliverToLocationIdentifier_ = "";
        dELIVERTOADDRESS_ = "";
        deliverToAddressLine1_ = "";
        deliverToAddressLine2_ = "";
        deliverToCity_ = "";
        deliverToPostCode_ = "";
        deliverToCountrySubdivision_ = "";
        deliverToAddressLine3_ = "";
        deliverToPartyName_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.example.DELIVERYINFORMATION.internal_static_com_example_DELIVERY_INFORMATION_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.example.DELIVERYINFORMATION.internal_static_com_example_DELIVERY_INFORMATION_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.example.DELIVERY_INFORMATION.class, com.example.DELIVERY_INFORMATION.Builder.class);
    }

    public static final int              DELIVERY_INFORMATION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile    java.lang.Object dELIVERYINFORMATION_              = "";

    /**
     * <code>string DELIVERY_INFORMATION = 1;</code>
     *
     * @return The dELIVERYINFORMATION.
     */
    @java.lang.Override
    public java.lang.String getDELIVERYINFORMATION() {
        java.lang.Object ref = dELIVERYINFORMATION_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            dELIVERYINFORMATION_ = s;
            return s;
        }
    }

    /**
     * <code>string DELIVERY_INFORMATION = 1;</code>
     *
     * @return The bytes for dELIVERYINFORMATION.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDELIVERYINFORMATIONBytes() {
        java.lang.Object ref = dELIVERYINFORMATION_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            dELIVERYINFORMATION_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int              DELIVER_TO_LOCATION_IDENTIFIER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile    java.lang.Object deliverToLocationIdentifier_                = "";

    /**
     * <code>string Deliver_to_location_identifier = 2;</code>
     *
     * @return The deliverToLocationIdentifier.
     */
    @java.lang.Override
    public java.lang.String getDeliverToLocationIdentifier() {
        java.lang.Object ref = deliverToLocationIdentifier_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            deliverToLocationIdentifier_ = s;
            return s;
        }
    }

    /**
     * <code>string Deliver_to_location_identifier = 2;</code>
     *
     * @return The bytes for deliverToLocationIdentifier.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDeliverToLocationIdentifierBytes() {
        java.lang.Object ref = deliverToLocationIdentifier_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            deliverToLocationIdentifier_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int              DELIVER_TO_ADDRESS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile    java.lang.Object dELIVERTOADDRESS_               = "";

    /**
     * <code>string DELIVER_TO_ADDRESS = 3;</code>
     *
     * @return The dELIVERTOADDRESS.
     */
    @java.lang.Override
    public java.lang.String getDELIVERTOADDRESS() {
        java.lang.Object ref = dELIVERTOADDRESS_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            dELIVERTOADDRESS_ = s;
            return s;
        }
    }

    /**
     * <code>string DELIVER_TO_ADDRESS = 3;</code>
     *
     * @return The bytes for dELIVERTOADDRESS.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDELIVERTOADDRESSBytes() {
        java.lang.Object ref = dELIVERTOADDRESS_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            dELIVERTOADDRESS_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int              DELIVER_TO_ADDRESS_LINE_1_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile    java.lang.Object deliverToAddressLine1_                 = "";

    /**
     * <code>string Deliver_to_address_line_1 = 4;</code>
     *
     * @return The deliverToAddressLine1.
     */
    @java.lang.Override
    public java.lang.String getDeliverToAddressLine1() {
        java.lang.Object ref = deliverToAddressLine1_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            deliverToAddressLine1_ = s;
            return s;
        }
    }

    /**
     * <code>string Deliver_to_address_line_1 = 4;</code>
     *
     * @return The bytes for deliverToAddressLine1.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDeliverToAddressLine1Bytes() {
        java.lang.Object ref = deliverToAddressLine1_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            deliverToAddressLine1_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int              DELIVER_TO_ADDRESS_LINE_2_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile    java.lang.Object deliverToAddressLine2_                 = "";

    /**
     * <code>string Deliver_to_address_line_2 = 5;</code>
     *
     * @return The deliverToAddressLine2.
     */
    @java.lang.Override
    public java.lang.String getDeliverToAddressLine2() {
        java.lang.Object ref = deliverToAddressLine2_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            deliverToAddressLine2_ = s;
            return s;
        }
    }

    /**
     * <code>string Deliver_to_address_line_2 = 5;</code>
     *
     * @return The bytes for deliverToAddressLine2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDeliverToAddressLine2Bytes() {
        java.lang.Object ref = deliverToAddressLine2_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            deliverToAddressLine2_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int              DELIVER_TO_CITY_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile    java.lang.Object deliverToCity_               = "";

    /**
     * <code>string Deliver_to_city = 6;</code>
     *
     * @return The deliverToCity.
     */
    @java.lang.Override
    public java.lang.String getDeliverToCity() {
        java.lang.Object ref = deliverToCity_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            deliverToCity_ = s;
            return s;
        }
    }

    /**
     * <code>string Deliver_to_city = 6;</code>
     *
     * @return The bytes for deliverToCity.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDeliverToCityBytes() {
        java.lang.Object ref = deliverToCity_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            deliverToCity_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int              DELIVER_TO_POST_CODE_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile    java.lang.Object deliverToPostCode_                = "";

    /**
     * <code>string Deliver_to_post_code = 7;</code>
     *
     * @return The deliverToPostCode.
     */
    @java.lang.Override
    public java.lang.String getDeliverToPostCode() {
        java.lang.Object ref = deliverToPostCode_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            deliverToPostCode_ = s;
            return s;
        }
    }

    /**
     * <code>string Deliver_to_post_code = 7;</code>
     *
     * @return The bytes for deliverToPostCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDeliverToPostCodeBytes() {
        java.lang.Object ref = deliverToPostCode_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            deliverToPostCode_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int              DELIVER_TO_COUNTRY_SUBDIVISION_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile    java.lang.Object deliverToCountrySubdivision_                = "";

    /**
     * <code>string Deliver_to_country_subdivision = 8;</code>
     *
     * @return The deliverToCountrySubdivision.
     */
    @java.lang.Override
    public java.lang.String getDeliverToCountrySubdivision() {
        java.lang.Object ref = deliverToCountrySubdivision_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            deliverToCountrySubdivision_ = s;
            return s;
        }
    }

    /**
     * <code>string Deliver_to_country_subdivision = 8;</code>
     *
     * @return The bytes for deliverToCountrySubdivision.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDeliverToCountrySubdivisionBytes() {
        java.lang.Object ref = deliverToCountrySubdivision_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            deliverToCountrySubdivision_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int              DELIVER_TO_ADDRESS_LINE_3_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile    java.lang.Object deliverToAddressLine3_                 = "";

    /**
     * <code>string Deliver_to_address_line_3 = 9;</code>
     *
     * @return The deliverToAddressLine3.
     */
    @java.lang.Override
    public java.lang.String getDeliverToAddressLine3() {
        java.lang.Object ref = deliverToAddressLine3_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            deliverToAddressLine3_ = s;
            return s;
        }
    }

    /**
     * <code>string Deliver_to_address_line_3 = 9;</code>
     *
     * @return The bytes for deliverToAddressLine3.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDeliverToAddressLine3Bytes() {
        java.lang.Object ref = deliverToAddressLine3_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            deliverToAddressLine3_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int              DELIVER_TO_PARTY_NAME_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile    java.lang.Object deliverToPartyName_                = "";

    /**
     * <code>string Deliver_to_party_name = 10;</code>
     *
     * @return The deliverToPartyName.
     */
    @java.lang.Override
    public java.lang.String getDeliverToPartyName() {
        java.lang.Object ref = deliverToPartyName_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            deliverToPartyName_ = s;
            return s;
        }
    }

    /**
     * <code>string Deliver_to_party_name = 10;</code>
     *
     * @return The bytes for deliverToPartyName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDeliverToPartyNameBytes() {
        java.lang.Object ref = deliverToPartyName_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            deliverToPartyName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dELIVERYINFORMATION_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, dELIVERYINFORMATION_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToLocationIdentifier_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 2, deliverToLocationIdentifier_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dELIVERTOADDRESS_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 3, dELIVERTOADDRESS_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToAddressLine1_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 4, deliverToAddressLine1_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToAddressLine2_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 5, deliverToAddressLine2_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToCity_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 6, deliverToCity_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToPostCode_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 7, deliverToPostCode_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToCountrySubdivision_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 8, deliverToCountrySubdivision_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToAddressLine3_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 9, deliverToAddressLine3_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToPartyName_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 10, deliverToPartyName_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dELIVERYINFORMATION_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, dELIVERYINFORMATION_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToLocationIdentifier_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(2, deliverToLocationIdentifier_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dELIVERTOADDRESS_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(3, dELIVERTOADDRESS_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToAddressLine1_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(4, deliverToAddressLine1_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToAddressLine2_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(5, deliverToAddressLine2_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToCity_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(6, deliverToCity_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToPostCode_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(7, deliverToPostCode_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToCountrySubdivision_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(8, deliverToCountrySubdivision_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToAddressLine3_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(9, deliverToAddressLine3_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deliverToPartyName_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(10, deliverToPartyName_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.example.DELIVERY_INFORMATION)) {
            return super.equals(obj);
        }
        com.example.DELIVERY_INFORMATION other = (com.example.DELIVERY_INFORMATION) obj;

        if (!getDELIVERYINFORMATION()
                .equals(other.getDELIVERYINFORMATION())) return false;
        if (!getDeliverToLocationIdentifier()
                .equals(other.getDeliverToLocationIdentifier())) return false;
        if (!getDELIVERTOADDRESS()
                .equals(other.getDELIVERTOADDRESS())) return false;
        if (!getDeliverToAddressLine1()
                .equals(other.getDeliverToAddressLine1())) return false;
        if (!getDeliverToAddressLine2()
                .equals(other.getDeliverToAddressLine2())) return false;
        if (!getDeliverToCity()
                .equals(other.getDeliverToCity())) return false;
        if (!getDeliverToPostCode()
                .equals(other.getDeliverToPostCode())) return false;
        if (!getDeliverToCountrySubdivision()
                .equals(other.getDeliverToCountrySubdivision())) return false;
        if (!getDeliverToAddressLine3()
                .equals(other.getDeliverToAddressLine3())) return false;
        if (!getDeliverToPartyName()
                .equals(other.getDeliverToPartyName())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DELIVERY_INFORMATION_FIELD_NUMBER;
        hash = (53 * hash) + getDELIVERYINFORMATION().hashCode();
        hash = (37 * hash) + DELIVER_TO_LOCATION_IDENTIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getDeliverToLocationIdentifier().hashCode();
        hash = (37 * hash) + DELIVER_TO_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getDELIVERTOADDRESS().hashCode();
        hash = (37 * hash) + DELIVER_TO_ADDRESS_LINE_1_FIELD_NUMBER;
        hash = (53 * hash) + getDeliverToAddressLine1().hashCode();
        hash = (37 * hash) + DELIVER_TO_ADDRESS_LINE_2_FIELD_NUMBER;
        hash = (53 * hash) + getDeliverToAddressLine2().hashCode();
        hash = (37 * hash) + DELIVER_TO_CITY_FIELD_NUMBER;
        hash = (53 * hash) + getDeliverToCity().hashCode();
        hash = (37 * hash) + DELIVER_TO_POST_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getDeliverToPostCode().hashCode();
        hash = (37 * hash) + DELIVER_TO_COUNTRY_SUBDIVISION_FIELD_NUMBER;
        hash = (53 * hash) + getDeliverToCountrySubdivision().hashCode();
        hash = (37 * hash) + DELIVER_TO_ADDRESS_LINE_3_FIELD_NUMBER;
        hash = (53 * hash) + getDeliverToAddressLine3().hashCode();
        hash = (37 * hash) + DELIVER_TO_PARTY_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getDeliverToPartyName().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.example.DELIVERY_INFORMATION parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.example.DELIVERY_INFORMATION parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.DELIVERY_INFORMATION parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.example.DELIVERY_INFORMATION parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.DELIVERY_INFORMATION parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.example.DELIVERY_INFORMATION parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.example.DELIVERY_INFORMATION parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.example.DELIVERY_INFORMATION parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.DELIVERY_INFORMATION parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.DELIVERY_INFORMATION parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.DELIVERY_INFORMATION parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.example.DELIVERY_INFORMATION parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.example.DELIVERY_INFORMATION prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code com.example.DELIVERY_INFORMATION}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.example.DELIVERY_INFORMATION)
            com.example.DELIVERY_INFORMATIONOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.example.DELIVERYINFORMATION.internal_static_com_example_DELIVERY_INFORMATION_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.example.DELIVERYINFORMATION.internal_static_com_example_DELIVERY_INFORMATION_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.example.DELIVERY_INFORMATION.class, com.example.DELIVERY_INFORMATION.Builder.class);
        }

        // Construct using com.example.DELIVERY_INFORMATION.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            dELIVERYINFORMATION_ = "";
            deliverToLocationIdentifier_ = "";
            dELIVERTOADDRESS_ = "";
            deliverToAddressLine1_ = "";
            deliverToAddressLine2_ = "";
            deliverToCity_ = "";
            deliverToPostCode_ = "";
            deliverToCountrySubdivision_ = "";
            deliverToAddressLine3_ = "";
            deliverToPartyName_ = "";
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.example.DELIVERYINFORMATION.internal_static_com_example_DELIVERY_INFORMATION_descriptor;
        }

        @java.lang.Override
        public com.example.DELIVERY_INFORMATION getDefaultInstanceForType() {
            return com.example.DELIVERY_INFORMATION.getDefaultInstance();
        }

        @java.lang.Override
        public com.example.DELIVERY_INFORMATION build() {
            com.example.DELIVERY_INFORMATION result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.example.DELIVERY_INFORMATION buildPartial() {
            com.example.DELIVERY_INFORMATION result = new com.example.DELIVERY_INFORMATION(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.example.DELIVERY_INFORMATION result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.dELIVERYINFORMATION_ = dELIVERYINFORMATION_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.deliverToLocationIdentifier_ = deliverToLocationIdentifier_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.dELIVERTOADDRESS_ = dELIVERTOADDRESS_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.deliverToAddressLine1_ = deliverToAddressLine1_;
            }
            if (((from_bitField0_ & 0x00000010) != 0)) {
                result.deliverToAddressLine2_ = deliverToAddressLine2_;
            }
            if (((from_bitField0_ & 0x00000020) != 0)) {
                result.deliverToCity_ = deliverToCity_;
            }
            if (((from_bitField0_ & 0x00000040) != 0)) {
                result.deliverToPostCode_ = deliverToPostCode_;
            }
            if (((from_bitField0_ & 0x00000080) != 0)) {
                result.deliverToCountrySubdivision_ = deliverToCountrySubdivision_;
            }
            if (((from_bitField0_ & 0x00000100) != 0)) {
                result.deliverToAddressLine3_ = deliverToAddressLine3_;
            }
            if (((from_bitField0_ & 0x00000200) != 0)) {
                result.deliverToPartyName_ = deliverToPartyName_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.example.DELIVERY_INFORMATION) {
                return mergeFrom((com.example.DELIVERY_INFORMATION) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.example.DELIVERY_INFORMATION other) {
            if (other == com.example.DELIVERY_INFORMATION.getDefaultInstance()) return this;
            if (!other.getDELIVERYINFORMATION().isEmpty()) {
                dELIVERYINFORMATION_ = other.dELIVERYINFORMATION_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (!other.getDeliverToLocationIdentifier().isEmpty()) {
                deliverToLocationIdentifier_ = other.deliverToLocationIdentifier_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (!other.getDELIVERTOADDRESS().isEmpty()) {
                dELIVERTOADDRESS_ = other.dELIVERTOADDRESS_;
                bitField0_ |= 0x00000004;
                onChanged();
            }
            if (!other.getDeliverToAddressLine1().isEmpty()) {
                deliverToAddressLine1_ = other.deliverToAddressLine1_;
                bitField0_ |= 0x00000008;
                onChanged();
            }
            if (!other.getDeliverToAddressLine2().isEmpty()) {
                deliverToAddressLine2_ = other.deliverToAddressLine2_;
                bitField0_ |= 0x00000010;
                onChanged();
            }
            if (!other.getDeliverToCity().isEmpty()) {
                deliverToCity_ = other.deliverToCity_;
                bitField0_ |= 0x00000020;
                onChanged();
            }
            if (!other.getDeliverToPostCode().isEmpty()) {
                deliverToPostCode_ = other.deliverToPostCode_;
                bitField0_ |= 0x00000040;
                onChanged();
            }
            if (!other.getDeliverToCountrySubdivision().isEmpty()) {
                deliverToCountrySubdivision_ = other.deliverToCountrySubdivision_;
                bitField0_ |= 0x00000080;
                onChanged();
            }
            if (!other.getDeliverToAddressLine3().isEmpty()) {
                deliverToAddressLine3_ = other.deliverToAddressLine3_;
                bitField0_ |= 0x00000100;
                onChanged();
            }
            if (!other.getDeliverToPartyName().isEmpty()) {
                deliverToPartyName_ = other.deliverToPartyName_;
                bitField0_ |= 0x00000200;
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            dELIVERYINFORMATION_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            deliverToLocationIdentifier_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 26: {
                            dELIVERTOADDRESS_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 26
                        case 34: {
                            deliverToAddressLine1_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 34
                        case 42: {
                            deliverToAddressLine2_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000010;
                            break;
                        } // case 42
                        case 50: {
                            deliverToCity_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000020;
                            break;
                        } // case 50
                        case 58: {
                            deliverToPostCode_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000040;
                            break;
                        } // case 58
                        case 66: {
                            deliverToCountrySubdivision_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000080;
                            break;
                        } // case 66
                        case 74: {
                            deliverToAddressLine3_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000100;
                            break;
                        } // case 74
                        case 82: {
                            deliverToPartyName_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000200;
                            break;
                        } // case 82
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private java.lang.Object dELIVERYINFORMATION_ = "";

        /**
         * <code>string DELIVERY_INFORMATION = 1;</code>
         *
         * @return The dELIVERYINFORMATION.
         */
        public java.lang.String getDELIVERYINFORMATION() {
            java.lang.Object ref = dELIVERYINFORMATION_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                dELIVERYINFORMATION_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string DELIVERY_INFORMATION = 1;</code>
         *
         * @return The bytes for dELIVERYINFORMATION.
         */
        public com.google.protobuf.ByteString
        getDELIVERYINFORMATIONBytes() {
            java.lang.Object ref = dELIVERYINFORMATION_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                dELIVERYINFORMATION_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string DELIVERY_INFORMATION = 1;</code>
         *
         * @param value The dELIVERYINFORMATION to set.
         * @return This builder for chaining.
         */
        public Builder setDELIVERYINFORMATION(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            dELIVERYINFORMATION_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string DELIVERY_INFORMATION = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDELIVERYINFORMATION() {
            dELIVERYINFORMATION_ = getDefaultInstance().getDELIVERYINFORMATION();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        /**
         * <code>string DELIVERY_INFORMATION = 1;</code>
         *
         * @param value The bytes for dELIVERYINFORMATION to set.
         * @return This builder for chaining.
         */
        public Builder setDELIVERYINFORMATIONBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            dELIVERYINFORMATION_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        private java.lang.Object deliverToLocationIdentifier_ = "";

        /**
         * <code>string Deliver_to_location_identifier = 2;</code>
         *
         * @return The deliverToLocationIdentifier.
         */
        public java.lang.String getDeliverToLocationIdentifier() {
            java.lang.Object ref = deliverToLocationIdentifier_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deliverToLocationIdentifier_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string Deliver_to_location_identifier = 2;</code>
         *
         * @return The bytes for deliverToLocationIdentifier.
         */
        public com.google.protobuf.ByteString
        getDeliverToLocationIdentifierBytes() {
            java.lang.Object ref = deliverToLocationIdentifier_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deliverToLocationIdentifier_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string Deliver_to_location_identifier = 2;</code>
         *
         * @param value The deliverToLocationIdentifier to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToLocationIdentifier(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            deliverToLocationIdentifier_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_location_identifier = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDeliverToLocationIdentifier() {
            deliverToLocationIdentifier_ = getDefaultInstance().getDeliverToLocationIdentifier();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_location_identifier = 2;</code>
         *
         * @param value The bytes for deliverToLocationIdentifier to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToLocationIdentifierBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            deliverToLocationIdentifier_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private java.lang.Object dELIVERTOADDRESS_ = "";

        /**
         * <code>string DELIVER_TO_ADDRESS = 3;</code>
         *
         * @return The dELIVERTOADDRESS.
         */
        public java.lang.String getDELIVERTOADDRESS() {
            java.lang.Object ref = dELIVERTOADDRESS_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                dELIVERTOADDRESS_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string DELIVER_TO_ADDRESS = 3;</code>
         *
         * @return The bytes for dELIVERTOADDRESS.
         */
        public com.google.protobuf.ByteString
        getDELIVERTOADDRESSBytes() {
            java.lang.Object ref = dELIVERTOADDRESS_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                dELIVERTOADDRESS_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string DELIVER_TO_ADDRESS = 3;</code>
         *
         * @param value The dELIVERTOADDRESS to set.
         * @return This builder for chaining.
         */
        public Builder setDELIVERTOADDRESS(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            dELIVERTOADDRESS_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>string DELIVER_TO_ADDRESS = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDELIVERTOADDRESS() {
            dELIVERTOADDRESS_ = getDefaultInstance().getDELIVERTOADDRESS();
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }

        /**
         * <code>string DELIVER_TO_ADDRESS = 3;</code>
         *
         * @param value The bytes for dELIVERTOADDRESS to set.
         * @return This builder for chaining.
         */
        public Builder setDELIVERTOADDRESSBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            dELIVERTOADDRESS_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        private java.lang.Object deliverToAddressLine1_ = "";

        /**
         * <code>string Deliver_to_address_line_1 = 4;</code>
         *
         * @return The deliverToAddressLine1.
         */
        public java.lang.String getDeliverToAddressLine1() {
            java.lang.Object ref = deliverToAddressLine1_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deliverToAddressLine1_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string Deliver_to_address_line_1 = 4;</code>
         *
         * @return The bytes for deliverToAddressLine1.
         */
        public com.google.protobuf.ByteString
        getDeliverToAddressLine1Bytes() {
            java.lang.Object ref = deliverToAddressLine1_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deliverToAddressLine1_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string Deliver_to_address_line_1 = 4;</code>
         *
         * @param value The deliverToAddressLine1 to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToAddressLine1(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            deliverToAddressLine1_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_address_line_1 = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDeliverToAddressLine1() {
            deliverToAddressLine1_ = getDefaultInstance().getDeliverToAddressLine1();
            bitField0_ = (bitField0_ & ~0x00000008);
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_address_line_1 = 4;</code>
         *
         * @param value The bytes for deliverToAddressLine1 to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToAddressLine1Bytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            deliverToAddressLine1_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        private java.lang.Object deliverToAddressLine2_ = "";

        /**
         * <code>string Deliver_to_address_line_2 = 5;</code>
         *
         * @return The deliverToAddressLine2.
         */
        public java.lang.String getDeliverToAddressLine2() {
            java.lang.Object ref = deliverToAddressLine2_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deliverToAddressLine2_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string Deliver_to_address_line_2 = 5;</code>
         *
         * @return The bytes for deliverToAddressLine2.
         */
        public com.google.protobuf.ByteString
        getDeliverToAddressLine2Bytes() {
            java.lang.Object ref = deliverToAddressLine2_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deliverToAddressLine2_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string Deliver_to_address_line_2 = 5;</code>
         *
         * @param value The deliverToAddressLine2 to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToAddressLine2(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            deliverToAddressLine2_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_address_line_2 = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDeliverToAddressLine2() {
            deliverToAddressLine2_ = getDefaultInstance().getDeliverToAddressLine2();
            bitField0_ = (bitField0_ & ~0x00000010);
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_address_line_2 = 5;</code>
         *
         * @param value The bytes for deliverToAddressLine2 to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToAddressLine2Bytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            deliverToAddressLine2_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        private java.lang.Object deliverToCity_ = "";

        /**
         * <code>string Deliver_to_city = 6;</code>
         *
         * @return The deliverToCity.
         */
        public java.lang.String getDeliverToCity() {
            java.lang.Object ref = deliverToCity_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deliverToCity_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string Deliver_to_city = 6;</code>
         *
         * @return The bytes for deliverToCity.
         */
        public com.google.protobuf.ByteString
        getDeliverToCityBytes() {
            java.lang.Object ref = deliverToCity_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deliverToCity_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string Deliver_to_city = 6;</code>
         *
         * @param value The deliverToCity to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToCity(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            deliverToCity_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_city = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDeliverToCity() {
            deliverToCity_ = getDefaultInstance().getDeliverToCity();
            bitField0_ = (bitField0_ & ~0x00000020);
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_city = 6;</code>
         *
         * @param value The bytes for deliverToCity to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToCityBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            deliverToCity_ = value;
            bitField0_ |= 0x00000020;
            onChanged();
            return this;
        }

        private java.lang.Object deliverToPostCode_ = "";

        /**
         * <code>string Deliver_to_post_code = 7;</code>
         *
         * @return The deliverToPostCode.
         */
        public java.lang.String getDeliverToPostCode() {
            java.lang.Object ref = deliverToPostCode_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deliverToPostCode_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string Deliver_to_post_code = 7;</code>
         *
         * @return The bytes for deliverToPostCode.
         */
        public com.google.protobuf.ByteString
        getDeliverToPostCodeBytes() {
            java.lang.Object ref = deliverToPostCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deliverToPostCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string Deliver_to_post_code = 7;</code>
         *
         * @param value The deliverToPostCode to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToPostCode(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            deliverToPostCode_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_post_code = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDeliverToPostCode() {
            deliverToPostCode_ = getDefaultInstance().getDeliverToPostCode();
            bitField0_ = (bitField0_ & ~0x00000040);
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_post_code = 7;</code>
         *
         * @param value The bytes for deliverToPostCode to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToPostCodeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            deliverToPostCode_ = value;
            bitField0_ |= 0x00000040;
            onChanged();
            return this;
        }

        private java.lang.Object deliverToCountrySubdivision_ = "";

        /**
         * <code>string Deliver_to_country_subdivision = 8;</code>
         *
         * @return The deliverToCountrySubdivision.
         */
        public java.lang.String getDeliverToCountrySubdivision() {
            java.lang.Object ref = deliverToCountrySubdivision_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deliverToCountrySubdivision_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string Deliver_to_country_subdivision = 8;</code>
         *
         * @return The bytes for deliverToCountrySubdivision.
         */
        public com.google.protobuf.ByteString
        getDeliverToCountrySubdivisionBytes() {
            java.lang.Object ref = deliverToCountrySubdivision_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deliverToCountrySubdivision_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string Deliver_to_country_subdivision = 8;</code>
         *
         * @param value The deliverToCountrySubdivision to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToCountrySubdivision(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            deliverToCountrySubdivision_ = value;
            bitField0_ |= 0x00000080;
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_country_subdivision = 8;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDeliverToCountrySubdivision() {
            deliverToCountrySubdivision_ = getDefaultInstance().getDeliverToCountrySubdivision();
            bitField0_ = (bitField0_ & ~0x00000080);
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_country_subdivision = 8;</code>
         *
         * @param value The bytes for deliverToCountrySubdivision to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToCountrySubdivisionBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            deliverToCountrySubdivision_ = value;
            bitField0_ |= 0x00000080;
            onChanged();
            return this;
        }

        private java.lang.Object deliverToAddressLine3_ = "";

        /**
         * <code>string Deliver_to_address_line_3 = 9;</code>
         *
         * @return The deliverToAddressLine3.
         */
        public java.lang.String getDeliverToAddressLine3() {
            java.lang.Object ref = deliverToAddressLine3_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deliverToAddressLine3_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string Deliver_to_address_line_3 = 9;</code>
         *
         * @return The bytes for deliverToAddressLine3.
         */
        public com.google.protobuf.ByteString
        getDeliverToAddressLine3Bytes() {
            java.lang.Object ref = deliverToAddressLine3_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deliverToAddressLine3_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string Deliver_to_address_line_3 = 9;</code>
         *
         * @param value The deliverToAddressLine3 to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToAddressLine3(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            deliverToAddressLine3_ = value;
            bitField0_ |= 0x00000100;
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_address_line_3 = 9;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDeliverToAddressLine3() {
            deliverToAddressLine3_ = getDefaultInstance().getDeliverToAddressLine3();
            bitField0_ = (bitField0_ & ~0x00000100);
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_address_line_3 = 9;</code>
         *
         * @param value The bytes for deliverToAddressLine3 to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToAddressLine3Bytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            deliverToAddressLine3_ = value;
            bitField0_ |= 0x00000100;
            onChanged();
            return this;
        }

        private java.lang.Object deliverToPartyName_ = "";

        /**
         * <code>string Deliver_to_party_name = 10;</code>
         *
         * @return The deliverToPartyName.
         */
        public java.lang.String getDeliverToPartyName() {
            java.lang.Object ref = deliverToPartyName_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deliverToPartyName_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string Deliver_to_party_name = 10;</code>
         *
         * @return The bytes for deliverToPartyName.
         */
        public com.google.protobuf.ByteString
        getDeliverToPartyNameBytes() {
            java.lang.Object ref = deliverToPartyName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deliverToPartyName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string Deliver_to_party_name = 10;</code>
         *
         * @param value The deliverToPartyName to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToPartyName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            deliverToPartyName_ = value;
            bitField0_ |= 0x00000200;
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_party_name = 10;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDeliverToPartyName() {
            deliverToPartyName_ = getDefaultInstance().getDeliverToPartyName();
            bitField0_ = (bitField0_ & ~0x00000200);
            onChanged();
            return this;
        }

        /**
         * <code>string Deliver_to_party_name = 10;</code>
         *
         * @param value The bytes for deliverToPartyName to set.
         * @return This builder for chaining.
         */
        public Builder setDeliverToPartyNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            deliverToPartyName_ = value;
            bitField0_ |= 0x00000200;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.example.DELIVERY_INFORMATION)
    }

    // @@protoc_insertion_point(class_scope:com.example.DELIVERY_INFORMATION)
    private static final com.example.DELIVERY_INFORMATION DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.example.DELIVERY_INFORMATION();
    }

    public static com.example.DELIVERY_INFORMATION getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DELIVERY_INFORMATION>
            PARSER = new com.google.protobuf.AbstractParser<DELIVERY_INFORMATION>() {
        @java.lang.Override
        public DELIVERY_INFORMATION parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<DELIVERY_INFORMATION> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DELIVERY_INFORMATION> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.example.DELIVERY_INFORMATION getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

