// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DELIVERY_INFORMATION.proto
// Protobuf Java Version: 4.27.3

package com.example;

public interface DELIVERY_INFORMATIONOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.DELIVERY_INFORMATION)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string DELIVERY_INFORMATION = 1;</code>
   * @return The dELIVERYINFORMATION.
   */
  java.lang.String getDELIVERYINFORMATION();
  /**
   * <code>string DELIVERY_INFORMATION = 1;</code>
   * @return The bytes for dELIVERYINFORMATION.
   */
  com.google.protobuf.ByteString
      getDELIVERYINFORMATIONBytes();

  /**
   * <code>string Deliver_to_location_identifier = 2;</code>
   * @return The deliverToLocationIdentifier.
   */
  java.lang.String getDeliverToLocationIdentifier();
  /**
   * <code>string Deliver_to_location_identifier = 2;</code>
   * @return The bytes for deliverToLocationIdentifier.
   */
  com.google.protobuf.ByteString
      getDeliverToLocationIdentifierBytes();

  /**
   * <code>string DELIVER_TO_ADDRESS = 3;</code>
   * @return The dELIVERTOADDRESS.
   */
  java.lang.String getDELIVERTOADDRESS();
  /**
   * <code>string DELIVER_TO_ADDRESS = 3;</code>
   * @return The bytes for dELIVERTOADDRESS.
   */
  com.google.protobuf.ByteString
      getDELIVERTOADDRESSBytes();

  /**
   * <code>string Deliver_to_address_line_1 = 4;</code>
   * @return The deliverToAddressLine1.
   */
  java.lang.String getDeliverToAddressLine1();
  /**
   * <code>string Deliver_to_address_line_1 = 4;</code>
   * @return The bytes for deliverToAddressLine1.
   */
  com.google.protobuf.ByteString
      getDeliverToAddressLine1Bytes();

  /**
   * <code>string Deliver_to_address_line_2 = 5;</code>
   * @return The deliverToAddressLine2.
   */
  java.lang.String getDeliverToAddressLine2();
  /**
   * <code>string Deliver_to_address_line_2 = 5;</code>
   * @return The bytes for deliverToAddressLine2.
   */
  com.google.protobuf.ByteString
      getDeliverToAddressLine2Bytes();

  /**
   * <code>string Deliver_to_city = 6;</code>
   * @return The deliverToCity.
   */
  java.lang.String getDeliverToCity();
  /**
   * <code>string Deliver_to_city = 6;</code>
   * @return The bytes for deliverToCity.
   */
  com.google.protobuf.ByteString
      getDeliverToCityBytes();

  /**
   * <code>string Deliver_to_post_code = 7;</code>
   * @return The deliverToPostCode.
   */
  java.lang.String getDeliverToPostCode();
  /**
   * <code>string Deliver_to_post_code = 7;</code>
   * @return The bytes for deliverToPostCode.
   */
  com.google.protobuf.ByteString
      getDeliverToPostCodeBytes();

  /**
   * <code>string Deliver_to_country_subdivision = 8;</code>
   * @return The deliverToCountrySubdivision.
   */
  java.lang.String getDeliverToCountrySubdivision();
  /**
   * <code>string Deliver_to_country_subdivision = 8;</code>
   * @return The bytes for deliverToCountrySubdivision.
   */
  com.google.protobuf.ByteString
      getDeliverToCountrySubdivisionBytes();

  /**
   * <code>string Deliver_to_address_line_3 = 9;</code>
   * @return The deliverToAddressLine3.
   */
  java.lang.String getDeliverToAddressLine3();
  /**
   * <code>string Deliver_to_address_line_3 = 9;</code>
   * @return The bytes for deliverToAddressLine3.
   */
  com.google.protobuf.ByteString
      getDeliverToAddressLine3Bytes();

  /**
   * <code>string Deliver_to_party_name = 10;</code>
   * @return The deliverToPartyName.
   */
  java.lang.String getDeliverToPartyName();
  /**
   * <code>string Deliver_to_party_name = 10;</code>
   * @return The bytes for deliverToPartyName.
   */
  com.google.protobuf.ByteString
      getDeliverToPartyNameBytes();
}
