// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DELIVERY_INFORMATION.proto
// Protobuf Java Version: 4.27.3

package com.example;

public final class DELIVERYINFORMATION {
  private DELIVERYINFORMATION() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      DELIVERYINFORMATION.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_DELIVERY_INFORMATION_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_DELIVERY_INFORMATION_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032DELIVERY_INFORMATION.proto\022\013com.exampl" +
      "e\"\337\002\n\024DELIVERY_INFORMATION\022\034\n\024DELIVERY_I" +
      "NFORMATION\030\001 \001(\t\022&\n\036Deliver_to_location_" +
      "identifier\030\002 \001(\t\022\032\n\022DELIVER_TO_ADDRESS\030\003" +
      " \001(\t\022!\n\031Deliver_to_address_line_1\030\004 \001(\t\022" +
      "!\n\031Deliver_to_address_line_2\030\005 \001(\t\022\027\n\017De" +
      "liver_to_city\030\006 \001(\t\022\034\n\024Deliver_to_post_c" +
      "ode\030\007 \001(\t\022&\n\036Deliver_to_country_subdivis" +
      "ion\030\010 \001(\t\022!\n\031Deliver_to_address_line_3\030\t" +
      " \001(\t\022\035\n\025Deliver_to_party_name\030\n \001(\tB\002P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_DELIVERY_INFORMATION_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_DELIVERY_INFORMATION_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_DELIVERY_INFORMATION_descriptor,
        new java.lang.String[] { "DELIVERYINFORMATION", "DeliverToLocationIdentifier", "DELIVERTOADDRESS", "DeliverToAddressLine1", "DeliverToAddressLine2", "DeliverToCity", "DeliverToPostCode", "DeliverToCountrySubdivision", "DeliverToAddressLine3", "DeliverToPartyName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
