// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example;

@kotlin.jvm.JvmName("-initializedELIVERYINFORMATION")
public inline fun dELIVERYINFORMATION(block: com.example.DELIVERY_INFORMATIONKt.Dsl.() -> kotlin.Unit): com.example.Test.DELIVERY_INFORMATION =
  com.example.DELIVERY_INFORMATIONKt.Dsl._create(com.example.Test.DELIVERY_INFORMATION.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.example.DELIVERY_INFORMATION`
 */
public object DELIVERY_INFORMATIONKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.Test.DELIVERY_INFORMATION.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.Test.DELIVERY_INFORMATION.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.Test.DELIVERY_INFORMATION = _builder.build()

    /**
     * `string DELIVERY_INFORMATION = 1;`
     */
    public var dELIVERYINFORMATION: kotlin.String
      @JvmName("getDELIVERYINFORMATION")
      get() = _builder.getDELIVERYINFORMATION()
      @JvmName("setDELIVERYINFORMATION")
      set(value) {
        _builder.setDELIVERYINFORMATION(value)
      }
    /**
     * `string DELIVERY_INFORMATION = 1;`
     */
    public fun clearDELIVERYINFORMATION() {
      _builder.clearDELIVERYINFORMATION()
    }

    /**
     * `string Deliver_to_location_identifier = 2;`
     */
    public var deliverToLocationIdentifier: kotlin.String
      @JvmName("getDeliverToLocationIdentifier")
      get() = _builder.getDeliverToLocationIdentifier()
      @JvmName("setDeliverToLocationIdentifier")
      set(value) {
        _builder.setDeliverToLocationIdentifier(value)
      }
    /**
     * `string Deliver_to_location_identifier = 2;`
     */
    public fun clearDeliverToLocationIdentifier() {
      _builder.clearDeliverToLocationIdentifier()
    }

    /**
     * `string DELIVER_TO_ADDRESS = 3;`
     */
    public var dELIVERTOADDRESS: kotlin.String
      @JvmName("getDELIVERTOADDRESS")
      get() = _builder.getDELIVERTOADDRESS()
      @JvmName("setDELIVERTOADDRESS")
      set(value) {
        _builder.setDELIVERTOADDRESS(value)
      }
    /**
     * `string DELIVER_TO_ADDRESS = 3;`
     */
    public fun clearDELIVERTOADDRESS() {
      _builder.clearDELIVERTOADDRESS()
    }

    /**
     * `string Deliver_to_address_line_1 = 4;`
     */
    public var deliverToAddressLine1: kotlin.String
      @JvmName("getDeliverToAddressLine1")
      get() = _builder.getDeliverToAddressLine1()
      @JvmName("setDeliverToAddressLine1")
      set(value) {
        _builder.setDeliverToAddressLine1(value)
      }
    /**
     * `string Deliver_to_address_line_1 = 4;`
     */
    public fun clearDeliverToAddressLine1() {
      _builder.clearDeliverToAddressLine1()
    }

    /**
     * `string Deliver_to_address_line_2 = 5;`
     */
    public var deliverToAddressLine2: kotlin.String
      @JvmName("getDeliverToAddressLine2")
      get() = _builder.getDeliverToAddressLine2()
      @JvmName("setDeliverToAddressLine2")
      set(value) {
        _builder.setDeliverToAddressLine2(value)
      }
    /**
     * `string Deliver_to_address_line_2 = 5;`
     */
    public fun clearDeliverToAddressLine2() {
      _builder.clearDeliverToAddressLine2()
    }

    /**
     * `string Deliver_to_city = 6;`
     */
    public var deliverToCity: kotlin.String
      @JvmName("getDeliverToCity")
      get() = _builder.getDeliverToCity()
      @JvmName("setDeliverToCity")
      set(value) {
        _builder.setDeliverToCity(value)
      }
    /**
     * `string Deliver_to_city = 6;`
     */
    public fun clearDeliverToCity() {
      _builder.clearDeliverToCity()
    }

    /**
     * `string Deliver_to_post_code = 7;`
     */
    public var deliverToPostCode: kotlin.String
      @JvmName("getDeliverToPostCode")
      get() = _builder.getDeliverToPostCode()
      @JvmName("setDeliverToPostCode")
      set(value) {
        _builder.setDeliverToPostCode(value)
      }
    /**
     * `string Deliver_to_post_code = 7;`
     */
    public fun clearDeliverToPostCode() {
      _builder.clearDeliverToPostCode()
    }

    /**
     * `string Deliver_to_country_subdivision = 8;`
     */
    public var deliverToCountrySubdivision: kotlin.String
      @JvmName("getDeliverToCountrySubdivision")
      get() = _builder.getDeliverToCountrySubdivision()
      @JvmName("setDeliverToCountrySubdivision")
      set(value) {
        _builder.setDeliverToCountrySubdivision(value)
      }
    /**
     * `string Deliver_to_country_subdivision = 8;`
     */
    public fun clearDeliverToCountrySubdivision() {
      _builder.clearDeliverToCountrySubdivision()
    }

    /**
     * `string Deliver_to_address_line_3 = 9;`
     */
    public var deliverToAddressLine3: kotlin.String
      @JvmName("getDeliverToAddressLine3")
      get() = _builder.getDeliverToAddressLine3()
      @JvmName("setDeliverToAddressLine3")
      set(value) {
        _builder.setDeliverToAddressLine3(value)
      }
    /**
     * `string Deliver_to_address_line_3 = 9;`
     */
    public fun clearDeliverToAddressLine3() {
      _builder.clearDeliverToAddressLine3()
    }

    /**
     * `string Deliver_to_party_name = 10;`
     */
    public var deliverToPartyName: kotlin.String
      @JvmName("getDeliverToPartyName")
      get() = _builder.getDeliverToPartyName()
      @JvmName("setDeliverToPartyName")
      set(value) {
        _builder.setDeliverToPartyName(value)
      }
    /**
     * `string Deliver_to_party_name = 10;`
     */
    public fun clearDeliverToPartyName() {
      _builder.clearDeliverToPartyName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.Test.DELIVERY_INFORMATION.copy(block: `com.example`.DELIVERY_INFORMATIONKt.Dsl.() -> kotlin.Unit): com.example.Test.DELIVERY_INFORMATION =
  `com.example`.DELIVERY_INFORMATIONKt.Dsl._create(this.toBuilder()).apply { block() }._build()

